# Generated by Django 4.1.2 on 2022-10-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
