# Generated by Django 4.1.2 on 2022-10-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_rename_release_data_toy_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='was_incluede_in_home',
            new_name='was_inclueded_in_home',
        ),
    ]
