# Generated by Django 4.1.2 on 2022-10-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_rename_was_incluede_in_home_toy_was_inclueded_in_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='was_inclueded_in_home',
            new_name='was_included_in_home',
        ),
    ]
